kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: kae-console
  name: kae-console
  namespace: kae
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kae-console
  template:
    metadata:
      labels:
        k8s-app: kae-console
    spec:
      containers:
      - name: kae-console
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
          protocol: TCP
        args:
        # Uncomment the following line to manually specify Kubernetes API server Host
        # If not specified, Dashboard will attempt to auto discover the API server and connect
        # to it. Uncomment only if the default does not work.
        # - --apiserver-host=http://my-address:port
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - name: docker-sock-volume
          mountPath: /var/run/docker.sock
        - name: kae-console-secret-vol
          mountPath: /etc/k8s-secret-volume
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "750m"
      - name: kae-pods-watcher
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ['sh', 'bin/run-pods-watcher']
        args:
        # Uncomment the following line to manually specify Kubernetes API server Host
        # If not specified, Dashboard will attempt to auto discover the API server and connect
        # to it. Uncomment only if the default does not work.
        # - --apiserver-host=http://my-address:port
        volumeMounts:
        - name: docker-sock-volume
          mountPath: /var/run/docker.sock
        - name: kae-console-secret-vol
          mountPath: /etc/k8s-secret-volume
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "750m"
      volumes:
      - name: docker-sock-volume
        hostPath:
          # location on host
          path: /var/run/docker.sock
          # this field is optional
          type: File
      - name: kae-console-secret-vol
        secret:
          secretName: kae-console
      serviceAccountName: kae-console-serviceaccount
      # Comment the following tolerations if console must not be deployed on master
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
