---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kae-console-serviceaccount
  namespace: kae

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kae-console-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - services
    verbs:
      - get
      - create
      - update
      - delete
      - patch
      - list
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - deployments
      - deployments/scale
      - deployments/rollback
      - ingresses
    verbs:
      - get
      - create
      - update
      - delete
      - patch
      - list
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - create
      - update
      - delete
      - patch
      - list
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: kae-console-role
  namespace: kae
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - services
    verbs:
      - get
      - create
      - update
      - delete
      - patch
      - list
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - jobs
      - deployments
      - deployments/scale
      - deployments/rollback
      - ingresses
    verbs:
      - get
      - create
      - update
      - delete
      - patch
      - list
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - create
      - update
      - delete
      - patch
      - list
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kae-console-role-nisa-binding
  namespace: kae
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kae-console-role
subjects:
  - kind: ServiceAccount
    name: kae-console-serviceaccount
    namespace: kae

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kae-console-clusterrole-nisa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kae-console-clusterrole
subjects:
  - kind: ServiceAccount
    name: kae-console-serviceaccount
    namespace: kae
